In [1]:
import numpy as np

In [2]:
import scipy
from scipy.io import loadmat
from data_generator import DataGenerator

In [4]:
from likelihood import GaussianLogLikelihood
from prior import ComplexityLogPrior
from posterior import LogPosterior
from mcmc import MCMC
from sequential_mc import SequentialMC
from util import generate_binary_coef

In [5]:
import matplotlib.pyplot as plt

In [6]:
data = loadmat('../data/phase_field_oneD_simulation_beginning_stage.mat')

In [5]:
data.keys()

dict_keys(['__header__', '__version__', '__globals__', 't', 'x', 'usol'])

In [6]:
u = data['usol']
t = np.squeeze(data['t'])
x = np.squeeze(data['x'])

In [7]:
from numerical_derivative import ChebyshevLocalFit_1D

In [8]:
width = 5

In [9]:
du_x, du_xx, du_t = ChebyshevLocalFit_1D(u, x, t, deg=3, width=width, diff=2)

In [10]:
u = u[width:(-width), width:(-width)]

In [11]:
n_samples = 5000

In [12]:
u = u.flatten()
du_x = du_x.flatten()
du_xx = du_xx.flatten()
du_t = du_t.flatten()

In [13]:
data = np.vstack([u,du_x,du_xx, du_t]).T

In [14]:
data.shape

(240100, 4)

In [15]:
np.random.seed(1001)

In [16]:
np.random.shuffle(data)

In [30]:
a = '22'

In [32]:
isinstance(a,str)

True

In [17]:
data = data[:n_samples]

In [18]:
data.shape

(5000, 4)

In [19]:
np.save('raw_data', data)

In [7]:
data = np.load('raw_data.npy')

In [8]:
dg = DataGenerator()

In [9]:
data[:,:-1].shape

(5000, 3)

In [10]:
X, names = dg(data[:,:-1], descriptions=['u','u_x','u_xx'] )

In [11]:
Y = data[:,-1]

In [20]:
prior = ComplexityLogPrior(method='num_terms', simplicity_preference=1.)

In [21]:
likelihood = GaussianLogLikelihood(X,Y)

In [22]:
posterior = LogPosterior(prior, likelihood)

In [23]:
import itertools

In [24]:
init_coefs = generate_binary_coef(1, len(names))

In [25]:
sequentialmc = SequentialMC(posterior=posterior,log_file='mc.csv')

In [26]:
names

[u,
 u_x,
 u_xx,
 u**2,
 u*u_x,
 u*u_xx,
 u_x**2,
 u_x*u_xx,
 u_xx**2,
 u**3,
 u**2*u_x,
 u**2*u_xx,
 u*u_x**2,
 u*u_x*u_xx,
 u*u_xx**2,
 u_x**3,
 u_x**2*u_xx,
 u_x*u_xx**2,
 u_xx**3]

In [38]:
len(names)

19

In [39]:
init_coefs[0] = np.array([1,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0])

In [ ]:
samples = sequentialmc(samples=init_coefs,beta0_nsteps=10,beta0to1_nsteps=100,beta1_nsteps=200, descriptions=names )

step: 0, beta:  0.000
step: 1, beta:  0.000
step: 2, beta:  0.000
step: 3, beta:  0.000
step: 4, beta:  0.000
step: 5, beta:  0.000
step: 6, beta:  0.000
step: 7, beta:  0.000
step: 8, beta:  0.000
step: 9, beta:  0.000
step: 10, beta:  0.000
step: 11, beta:  0.010
step: 12, beta:  0.020
step: 13, beta:  0.030
step: 14, beta:  0.040
step: 15, beta:  0.051
step: 16, beta:  0.061
step: 17, beta:  0.071
step: 18, beta:  0.081
step: 19, beta:  0.091
step: 20, beta:  0.101
step: 21, beta:  0.111
step: 22, beta:  0.121
step: 23, beta:  0.131
step: 24, beta:  0.141
step: 25, beta:  0.152
step: 26, beta:  0.162
step: 27, beta:  0.172
step: 28, beta:  0.182
step: 29, beta:  0.192
step: 30, beta:  0.202
step: 31, beta:  0.212
step: 32, beta:  0.222
step: 33, beta:  0.232
step: 34, beta:  0.242
step: 35, beta:  0.253
step: 36, beta:  0.263
step: 37, beta:  0.273
step: 38, beta:  0.283
step: 39, beta:  0.293
step: 40, beta:  0.303
step: 41, beta:  0.313
step: 42, beta:  0.323
step: 43, beta:  0.33

In [29]:
import pandas as pd

In [32]:
data = pd.read_csv('mc.csv', header=0)

In [33]:
data

step                                           sample 0  \
0       0                                                  0   
1       1  0.796365736741299*u**3 - 3.15891432628123*u**2...   
2       2  7.60768947191288*u**2*u_x - 17829.8130616442*u...   
3       3  0.0123653417956881*u**2 + 2668.40280336591*u*u...   
4       4  -16.129105439918*u**2*u_x - 121212.014010917*u...   
..    ...                                                ...   
396   396  -1.02209923989814*u**3 - 0.57354354290876*u**2...   
397   397  11.2163446778825*u**2*u_x + 0.581024738550646*...   
398   398  -35.0205452130254*u**2*u_xx + 0.53038671545779...   
399   399  -304.474094052787*u*u_x**2 - 510.925745556824*...   
400   400  455.018268555224*u**2*u_xx + 0.629012726134742...   

                                              sample 1  \
0            0.0256136998623041*u - 0.0189419221597271   
1    24.6093628003228*u**2*u_x + 144.333050271164*u...   
2    0.0151112149883552*u**2 + 69.874609616469*u*u_...   
3    -1.02052070570187*u**3 - 0.51958605124456*u**2...   
4    -1.03252922150293*u**3 + 1.04132487753571*u**2...   
..                                                 ...   
396  4.35585505749627*u**2*u_x + 508.374483434512*u...   
397  -18.3134809263354*u**2*u_x + 923.845922166882*...   
398  1.21977841370213*u**3 + 93.28059942571*u**2*u_...   
399  0.136095344425372*u**3 - 0.133189784048484*u**...   
400  0.773738710821334*u**3 - 0.757819925117817*u**...   

                                              sample 2  \
0             0.0083895697790101 - 3.9822356165047*u_x   
1    -1.01212217455373*u**3 - 0.264787542798352*u**...   
2    0.0178974504716337*u**2 + 2187.12414179433*u*u...   
3    -0.959276700476131*u**3 + 0.275633404004468*u*...   
4    1.03682162948468*u**3 + 15.6011349377403*u**2*...   
..                                                 ...   
396  -0.47208437386924*u**3 + 0.474826720446664*u**...   
397  0.00118982690768843*u**3 - 18805.8281970285*u*...   
398  0.83592474545959*u**2 + 4464.16416845002*u*u_x...   
399  -1.14132544717722*u**3 - 0.312864914697048*u**...   
400  1.84403143791399*u**3 + 51.8152318584333*u**2*...   

                                              sample 3  \
0           8.5709133879994e-5 - 19.8486850396247*u_xx   
1    0.498709817083913*u**3 + 34.5800283701242*u**2...   
2    1.84177518517871*u**3 + 57.5317120184227*u**2*...   
3    0.288186881085897*u**3 - 139.634478420815*u**2...   
4    56.6913627190049*u**2*u_x + 0.0100722129748675...   
..                                                 ...   
396  -1.02180048091444*u**3 - 0.543916471940113*u**...   
397  2.30216470805462*u**3 + 75.6192580839163*u**2*...   
398  -0.973653406395869*u**3 + 0.25328195332349*u**...   
399  -1.17590691229754*u**3 + 2.15472092903443*u**2...   
400  945.719275253651*u**2*u_xx - 3205.76134276949*...   

                                              sample 4  \
0         0.0310305444817164*u**2 - 0.0221055406291764   
1    -82.3162037325259*u**2*u_xx - 53.5171995127869...   
2    20.3517144686202*u**2*u_x - 493.347386071755*u...   
3    0.469733781506759*u**3 - 1.30573316184503*u**2...   
4    599.655483196295*u**2*u_xx + 9485.67770185567*...   
..                                                 ...   
396  -616.288577023758*u*u_x**2 + 15.651965295248*u...   
397  1.15382756324248*u**3 + 54.1894009469672*u**2*...   
398  2.73845767056776*u**2*u_x + 17.8346167382689*u...   
399  -1.00232036777473*u**3 + 0.52277171206186*u**2...   
400  1133.87599703229*u*u_x**2 - 652.901111531773*u...   

                                              sample 5  \
0        -5.41989886281898*u*u_x + 0.00565334578072126   
1    35.413980550162*u**2*u_x + 1380.02087244515*u*...   
2    0.167524220511345*u**3 - 253201.200391612*u*u_...   
3    0.574492350254202*u**3 - 3.27126951548962*u**2...   
4    -136.085907007764*u**2*u_xx + 1870.09331022286...   
..                                                 ...   
396  -3865.83612989678*u*u_x*u_xx - 6.2074

In [37]:
data.values[-1]

array([400,
       '455.018268555224*u**2*u_xx + 0.629012726134742*u**2 + 8.30864405201357*u*u_x - 478.540689427039*u*u_xx - 0.626166816453172*u - 2013.18239741741*u_x**3 - 97284.0893497997*u_x**2*u_xx + 556281.759580422*u_x*u_xx**2 + 7340.42502564581*u_x*u_xx - 25870.0647088849*u_xx**2 - 12.084520400237*u_xx + 0.00813896773105892',
       '0.773738710821334*u**3 - 0.757819925117817*u**2 - 2735.03320803586*u*u_x*u_xx + 9.33531268250373*u*u_x - 83364.8025086424*u*u_xx**2 + 175119.326273052*u_x**2*u_xx - 163.314757582846*u_x**2 + 1231153.18025563*u_x*u_xx**2 - 4995.58785983648*u_x*u_xx - 0.00378389167553842',
       '1.84403143791399*u**3 + 51.8152318584333*u**2*u_x - 1.83894383782383*u**2 - 526.052218633697*u*u_x**2 - 234071.969992467*u*u_xx**2 + 328.739487426873*u*u_xx + 135674.020322036*u_x**2*u_xx - 3540.38088552918*u_x*u_xx - 20535811.1332133*u_xx**3 + 124050.323791814*u_xx**2 - 138.251077664269*u_xx + 0.00513366227607125',
       '945.719275253651*u**2*u_xx - 3205.76134276949*u*u_x

In [17]:
data = pd.read_csv("mc.log", header=0, delim_whitespace=True)

In [18]:
pd.set_option('display.max_columns', None)

In [19]:
data

step  weight_1  weight_2   weight_3  weight_4  weight_5  weight_6  \
0     0 -0.902409       0.0  10.296157  1.907862       0.0       0.0   

   weight_7  weight_8  weight_9  weight_10  weight_11  weight_12  weight_13  \
0       0.0       0.0       0.0   -1.00538        0.0        0.0        0.0   

   weight_14  weight_15  weight_16  weight_17  weight_18  weight_19      bias  \
0        0.0        0.0        0.0        0.0        0.0        0.0  0.009829   

   accp_prob  logPrior  logLikelihood  logPosterior  
0        1.0      -0.0         -0.215        -0.215

In [20]:
type(names[0])

sympy.core.symbol.Symbol

In [31]:
a= np.array([[1,2,3,1],[1,2,3,1]])

In [32]:
a

array([[1, 2, 3, 1],
       [1, 2, 3, 1]])

In [33]:
np.unique(a,return_counts=True,axis=1)

(array([[1, 2, 3],
        [1, 2, 3]]), array([2, 1, 1]))

In [34]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])